### ISSUE TITLE
Full stack harjoitustyön katselmointi

### ISSUE THREAD

**Issue by outisa** [glomfigli/glomfig#154]
Hei @sneikki ja @jvs23!

Katselmoin teidän Full stack kurssin harjoitustyönne ja ohessa kommentteja niin koodista ja reposta kuin sovelluksestakin. Teidän ei tarvitse tehdä enää mitään suoritusmerkin saamiseksi, mutta voitte halutessanne käyttää oheisia kommentteja hyödyksi niin tässä kuin tulevissa projekteissanne.

Repositorio on siisti, kansiorakenne ja README ovat erinomaisia. Kannattaa lisätä työllenne vielä lisenssi, kuten esimerkiksi MIT.

**Sovellus**

Käytetty selain oli Firefox
- Sovelluksen ulkoasu on hieno ja ja helposti lähestyttävä
- Kun käyttäjä on luonut tunnuksen ja kirjautunut sitään, niin join now on edelleen esillä. Tämä voisi olla ehkäpä piilotettuna sisäänkirjautuneilla käyttäjillä.
- Uusien config entiteetien luonti ja poisto onnistuu ongelmitta
- Quick start osio on erittäin hyvä idea, se antaa käyttäjälle kätevän silmäyksen siitä, mitä sovelluksella voi tehdä.
- Jos klikkaan hampurilaismenua ja sieltä Explore, Recent tai Popular, niin selaimessa renderöityy aina recent configurations.

Jatkokehitysideoita:
- Käyttäjän mahdollisuus poistaa oma profiili 

**Koodi**
- Hyvien käytänteiden mukaisesti debuggaukseen käytetyt console.logit tulisi poistaa tuotantokoodista. [Esimerkiksi](https://github.com/glomfigli/glomfig/blob/4e1dd035ffef65ec4c2e76f9fd8c82ee70a83720/client/src/views/Register.tsx#L21) luodessani uutta tunnusta, näen selaimen konsolissa luomani käyttäjäobjektin.
- Tyylejä ja tyyppejä on käytetty koodissa hyvin ja tyylitiedostot on nimetty selkeästi, joten niiden löytäminen tarvittaessa on helppoa.
- Komponenttien ja tiedostojen nimeäminen on fiksua
- En tiedä tarkalleen, että miten teidän Dockerfile on muotoiltu tuotannossa, mutta siellä itse käyttäisin `npm install` sijaan `npm ci`. lisätietoja [täältä](https://docs.npmjs.com/cli/v9/commands/npm-ci)

Yleisesti on hienoa, että olette ottaneet käyttöön CI putken, Redisin ja Dockerin. Näiden osaamisesta on varmasti jatkossakin teille hyötyä.

Kaiken kaikkiaan hienoa työtä!

**Comment by JVS23** [comment]
Kiitoksia arvioinnista ja kehitysehdotuksista!
